# Generated by Django 4.0.3 on 2022-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='network_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='network_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
