# Generated by Django 4.0.3 on 2022-04-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_frontside', models.ImageField(upload_to='images/Nationaldetails/image_frontside')),
                ('image_backside', models.ImageField(upload_to='images/Nationaldetails/image_backside')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('service', models.IntegerField(choices=[(1, 'Web developer'), (2, 'SEO Expert'), (3, 'Mobile Apps Developments'), (4, 'Graphic Designer'), (5, 'Manager')])),
                ('images', models.ImageField(default='', upload_to='images/portfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('massege', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('job_budgets', models.IntegerField(blank=True, null=True)),
                ('buget', models.IntegerField(blank=True, default=5, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Government_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_Num', models.CharField(help_text='xxxxx-xxxxxxx-x', max_length=15, unique=True)),
                ('image_frontside', models.ImageField(blank=True, upload_to='images/Nationaldetails/image_frontside')),
                ('image_backside', models.ImageField(blank=True, upload_to='images/Nationaldetails/image_backside')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Government', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
